#!/usr/bin/with-contenv bash

if [ ! -e "/config/www/grav" ]; then
    cp -R /app/grav /config/www
fi

if ! grep -q 'config-v1' /config/nginx/default; then
    cp /defaults/default /config/nginx
fi

# make folders
mkdir -p \
	/config/crontabs

# if root crontabs do not exist in config
# copy root crontab from system
if [[ ! -f /config/crontabs/root ]] && \
crontab -l -u root; then
	crontab -l -u root > /config/crontabs/root
fi

# if root crontabs still do not exist in config (were not copied from system)
# copy root crontab from included defaults
[[ ! -f /config/crontabs/root ]] && \
	cp /defaults/crontabs/root /config/crontabs/

# if abc crontabs do not exist in config
# copy abc crontab from system
if [[ ! -f /config/crontabs/abc ]] && \
crontab -l -u abc; then
	crontab -l -u abc > /config/crontabs/abc
fi

# if abc crontabs still do not exist in config (were not copied from system)
# copy abc crontab from included defaults
[[ ! -f /config/crontabs/abc ]] && \
	cp /defaults/crontabs/abc /config/crontabs/

# import user crontabs
crontab -u root /config/crontabs/root
crontab -u abc /config/crontabs/abc

# permissions
chown -R abc:abc \
	/config